name: Container
on: push

jobs:
  node-docker:
    runs-on: ubuntu-latest
    #can have it as a string as shown below
    #container: node:14-alpine3.16
    #or as an object
    container:
      image: node:14-alpine3.16
    steps:
      - name: Log Node version
        run: |
          node -v
          cat /etc/os-release

