name: Multiplecontainers
on: push

jobs:
  docker-steps:
    runs-on: ubuntu-latest
    container:
      image: node:10.18.0-jessie
    steps:
      - name: log node version
        run: node -v
      - name: step with docker
        uses: docker://node:12.14.1-alpine3.10
        with:
          entrypoint: "/bin/echo"
          args: "Hello World!!!"
      - name: Log node version
        uses: docker://node:12.14.1-alpine3.10
        with:
          #type -a node to get he below path, since yml no need for "" for path
          entrypoint: /usr/local/bin/node
          args: -v
      #The files needs to be checked out since we have an executable script file
      - uses: actions/checkout@v1
      - name: Run a script
        uses: docker://node:12.14.1-alpine3.10
        with:
          #using the script file, this script file shall be converted to an executable b4 committing using chmod command
          entrypoint: ./script.sh
          args: "some string"
  node-dockers:
    runs-on: ubuntu-latest
    services:
      app:
        image: alialaa17/node-api
        ports:
          - 3001:3000
      mongo:
        image: mongo
        ports:
          - "27017:27017"
    steps:
      - name: Post a User
        run: 'curl -X POST http://localhost:3001/api/user -H "Content-Type: application/json" -d "{"username": "hello", "address": "avbn"}"'
      - name: Get Users
        run: curl http://localhost:3001/api/users